### ISSUE TITLE
Problem mit URLDownloader in yEd recipe

### ISSUE THREAD

**Issue by xastherion** [autopkg/48kRAM-recipes#10]
Hi 48rRAM

I am usind your recipe for yed, but first i become this error:
_------------------------
>>> ~ >>> autopkg run yed.munki.recipe
Processing yed.munki.recipe...
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.
The following recipes failed:
    yed.munki.recipe
        Error in local.munki.yed: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Nothing downloaded, packaged or imported._
------------------------

I think that is because yed people change his URL: In URLDownloader is /products/ and actually should be /resources/.
I change this path in URLDownloader.py and i think is ok, but now i become a new problem:

_------------------------
>>> ~ >>> autopkg run yed.munki.recipe
Processing yed.munki.recipe...
creating pkginfo for /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg failed: ERROR: hdiutil error hdiutil: imageinfo failed - image not recognized
 with image /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg.
ERROR: hdiutil error hdiutil: imageinfo failed - image not recognized
 with image /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg.
ERROR: Error: "hdiutil: attach failed - image not recognized" while mounting yEd.dmg.
Could not mount /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg!
Failed.
The following recipes failed:
    yed.munki.recipe
        Error in local.munki.yed: Processor: MunkiImporter: Error: creating pkginfo for /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg failed: ERROR: hdiutil error hdiutil: imageinfo failed - image not recognized
         with image /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg.
        ERROR: hdiutil error hdiutil: imageinfo failed - image not recognized
         with image /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg.
        ERROR: Error: "hdiutil: attach failed - image not recognized" while mounting yEd.dmg.
        Could not mount /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg!
The following new items were downloaded:
    Download Path
    -------------
    /DATA/AutoPkg/Cache/local.munki.yed/downloads/yEd.dmg
------------------------_

I look into the cache but this yEd.dmg is really wrong. Do you now why?

**Comment by 48kRAM** [comment]
The issue is that they changed the embedded JRE from 8 to 10 and thus the product download URL changed. I've fixed this issue in the downloader recipe.

**Comment by xastherion** [comment]
now is all right! Thanks!
