### ISSUE TITLE
OSXFuse Non-Dev Release

### ISSUE THREAD

**Issue by ahaupt11** [autopkg/48kRAM-recipes#2]
Question, is there a way to change the OSXFuse recipe to not grab the dev releases, but just the stable ones?

Thanks!

**Comment by 48kRAM** [comment]
I've just pushed an update to the OSXFuse recipe that excludes pre-releases by default using the new GitHubReleasesInfoProvider processor.

_however_ - it appears that OSXFuse is no longer providing binary releases for anything but their pre-releases anymore, so this recipe now downloads nothing by default. There's nothing I can do about that, so I'd suggest you open an issue with the OSXFuse team. I have actually abandoned OSXFuse as the fuse-ext2 driver I was using it for is not worth fooling with anymore.

**Comment by 48kRAM** [comment]
The OSXFUSE project now has proper releases. Tested working with this update. Closing necro-issue :)
