### ISSUE TITLE
osxfuse/macfuse v4

### ISSUE THREAD

**Issue by timnottom** [autopkg/48kRAM-recipes#20]
Hi, osxfuse has changed from version 3 to version 4, and now has a different name: macfuse. I'm kind of new into this but I've forked this repo and created macfuse by copying and adjusting the osxfuse recipes. I think this should make it work, but I'm not sure if the installer_choices should be adjusted or if the wording in the description is ok. If it is, what would be the next step? 

Let me know what i can do to make this work!

here's the fork: https://github.com/timnottom/48kRAM-recipes/tree/master/macFUSE

Tim

**Comment by 48kRAM** [comment]
Hi Tim,

I actually don't maintain any Mac systems anymore, so these recipes are basically unmaintained except for a few pull requests that I get every year. I don't have a way of checking the installer choices, but if you report that they work for you, I'm happy to accept a pull-request for this recipe.

Thanks!

-Josh

**Comment by timnottom** [comment]
Thanks Josh,

since this is my first real go at this, i'll ask someone in the macadmins
Slack if they want to check this first.

Tim

**Comment by timnottom** [comment]
This issue is resolved by adding the macfuse recipes to the repo. Thanks @48kRAM!
