### ISSUE TITLE
Strict verification fails with current version of Emacs

### ISSUE THREAD

**Issue by undulat** [autopkg/48kRAM-recipes#27]
When AutoPkg runs the recipe it fails with a strict verification fail
https://github.com/autopkg/48kRAM-recipes/blob/master/Emacs/EmacsForMacOSX.download.recipe

**Comment by stefanj135** [comment]
Yes we have this issue also with code signature fails.

EmacsURLProvider: Found URL as https://emacsformacosx.com/emacs-builds/Emacs-27.2-3-universal.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /srv/autopkg/Cache/local.munki.EmacsForMacOSX/downloads/Emacs_For_Mac_OS_X.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /srv/autopkg/Cache/local.munki.EmacsForMacOSX/downloads/Emacs_For_Mac_OS_X.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification enabled...
CodeSignatureVerifier: /private/tmp/dmg.821Tda/Emacs.app: a sealed resource is missing or invalid
CodeSignatureVerifier: file added: /private/tmp/dmg.821Tda/Emacs.app/Contents/MacOS/._Emacs.pdmp
CodeSignatureVerifier: file added: /private/tmp/dmg.821Tda/Emacs.app/Contents/MacOS/libexec-arm64-12/._rcs2log
CodeSignatureVerifier: file added: /private/tmp/dmg.821Tda/Emacs.app/Contents/MacOS/._Emacs-x86_64-10_14.pdmp
CodeSignatureVerifier: file added: /private/tmp/dmg.821Tda/Emacs.app/Contents/MacOS/._Emacs-arm64-12.pdmp
CodeSignatureVerifier: file added: /private/tmp/dmg.821Tda/Emacs.app/Contents/MacOS/libexec-x86_64-10_11/._rcs2log
CodeSignatureVerifier: file added: /private/tmp/dmg.821Tda/Emacs.app/Contents/MacOS/libexec-x86_64-10_14/._rcs2log
CodeSignatureVerifier: file added: /private/tmp/dmg.821Tda/Emacs.app/Contents/MacOS/._Emacs-x86_64-10_11.pdmp
Receipt written to /srv/autopkg/Cache/local.munki.EmacsForMacOSX/receipts/EmacsForMacOSX-receipt-20220105-200706.plist

The following recipes failed:
    EmacsForMacOSX.munki
        Error in local.munki.EmacsForMacOSX: Processor: CodeSignatureVerifier: Error: Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

**Comment by homebysix** [comment]
It looks like this was an issue on the developer's end, which is now resolved.

```
% autopkg run -vvq 'Emacs/EmacsForMacOSX.download.recipe'
Processing Emacs/EmacsForMacOSX.download.recipe...
WARNING: Emacs/EmacsForMacOSX.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
EmacsURLProvider
{'Input': {}}
EmacsURLProvider: Found URL as https://emacsformacosx.com/emacs-builds/Emacs-29.4-1-universal.dmg
{'Output': {'url': 'https://emacsformacosx.com/emacs-builds/Emacs-29.4-1-universal.dmg'}}
URLDownloader
{'Input': {'filename': 'EmacsForMacOSX.dmg',
           'url': 'https://emacsformacosx.com/emacs-builds/Emacs-29.4-1-universal.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Fri, 02 Aug 2024 21:54:38 GMT
URLDownloader: Storing new ETag header: "603cedb-61eba5faa2380"
URLDownloader: Downloaded ~/Library/AutoPkg/Cache/com.github.48kRAM.autopkg.download.emacsformacosx/downloads/EmacsForMacOSX.dmg
{'Output': {'download_changed': True,
            'etag': '"603cedb-61eba5faa2380"',
            'last_modified': 'Fri, 02 Aug 2024 21:54:38 GMT',
            'pathname': '~/Library/AutoPkg/Cache/com.github.48kRAM.autopkg.download.emacsformacosx/downloads/EmacsForMacOSX.dmg',
            'url_downloader_summary_result': {'data': {'download_path': '~/Library/AutoPkg/Cache/com.github.48kRAM.autopkg.download.emacsformacosx/downloads/EmacsForMacOSX.dmg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': '~/Library/AutoPkg/Cache/com.github.48kRAM.autopkg.download.emacsformacosx/downloads/EmacsForMacOSX.dmg/Emacs.app',
           'requirement': 'identifier "org.gnu.Emacs" and anchor apple generic '
                          'and certificate 1[field.1.2.840.113635.100.6.2.6] '
                          '/* exists */ and certificate '
                          'leaf[field.1.2.840.113635.100.6.1.13] /* exists */ '
                          'and certificate leaf[subject.OU] = "5BRAQAFB8B"',
           'strict_verification': True}}
CodeSignatureVerifier: Mounted disk image ~/Library/AutoPkg/Cache/com.github.48kRAM.autopkg.download.emacsformacosx/downloads/EmacsForMacOSX.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification enabled...
CodeSignatureVerifier: /private/tmp/dmg.ITXYhc/Emacs.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.ITXYhc/Emacs.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.ITXYhc/Emacs.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
Receipt written to ~/Library/AutoPkg/Cache/com.github.48kRAM.autopkg.download.emacsformacosx/receipts/EmacsForMacOSX.download-receipt-20241224-165107.plist

The following new items were downloaded:
    Download Path                                                                                                       
    -------------                                                                                                       
    ~/Library/AutoPkg/Cache/com.github.48kRAM.autopkg.download.emacsformacosx/downloads/EmacsForMacOSX.dmg
```
