### ISSUE TITLE
com.github.48kRAM.autopkg.download.yed error - No match found

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/48kRAM-recipes#32]
Hi,

It looks like something may have changed on yED's side as the .download recipe now fails with:
`com.github.48kRAM.autopkg.download.yed
        Error in com.github.48kRAM.autopkg.download.yed: Processor: URLTextSearcher: Error: No match found on URL: https://www.yworks.com/products/yed/download`

I'm going to see if I can get a resolution and PR a fix

**Comment by Daz-wallace** [comment]
Hmm also looks like they've split the install into Intel and Apple Silicon (ARM)

**Comment by Daz-wallace** [comment]
See https://github.com/autopkg/48kRAM-recipes/pull/35

**Comment by homebysix** [comment]
Should be fixed by #37 too, which supports multiple architectures.
